OAP-38: Add /ngrams endpoint to API
EbookFoundation/oapen-suggestion-service pull request #19
Opened 2022-11-01 05:01 UTC by peterrauscher

Adds the following endpoint to the API:
`/api/{handle}/ngrams`

Also removes redundant .js clean and seed tasks, handles URL-escaping of handles, and updates README to reflect changes.

2022-11-01 11:25 UTC, justinoboyle approved these changes

2022-11-01 13:49 UTC, j-sofia requested changes

2022-11-01 13:49 UTC, j-sofia commented on api/db/data.js
> +  const query = new PQ({ text: "SELECT * FROM oapen_suggestions.ngrams WHERE handle = $1", values: [id] });
querySuggestions function needs handle instead of item_id

2022-11-01 13:49 UTC, j-sofia commented on api/routes.js
>  router.get("/:handle", async (req, res) => {
Can use regex to avoid encoding the slash:
"/:handle([0-9]+.[0-9]+.[0-9]+/[0-9]+)"

2022-11-01 13:49 UTC, j-sofia commented on api/routes.js
>      if (responseData.error && responseData.error.name === pgp.errors.QueryResultError.name) {
need const pgp = require("pg-promise"); at the top of the file

2022-11-09 23:44 UTC, peterrauscher commented
Resolves OAP-38 and resolves OAP-42

2022-11-09 23:45 UTC, merged